site_name: memoraxx
docs_dir: doc
nav:
  - Home: README.md
  - API Reference: API.md
  - Architecture: ARCHITECTURE.md
  - Docker Setup: DOCKER.md
  - Examples: EXAMPLES.md
  - Contributing: ../CONTRIBUTING.md
theme: readthedocs
